// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package extensions.actions;

import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import com.maxmind.geoip2.DatabaseReader;
import com.maxmind.geoip2.model.CityResponse;
import com.maxmind.geoip2.record.City;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_GetCityByIp extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String IpAdress;

	public JA_GetCityByIp(
		IContext context,
		java.lang.String _ipAdress
	)
	{
		super(context);
		this.IpAdress = _ipAdress;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		 String GEO_LITE_DB_PATH = "GeoLite2-City.mmdb";
		 try {
	            File geoLiteDb = new File(Core.getConfiguration().getResourcesPath() + "/" + GEO_LITE_DB_PATH);
	            DatabaseReader databaseReader = new DatabaseReader.Builder(geoLiteDb).build();
	            InetAddress inetAddress = InetAddress.getByName(IpAdress);

	            CityResponse cityResponse = databaseReader.city(inetAddress);
	            City city = cityResponse.getCity();

	            return city.getName();
	        } catch (IOException e) {
	            throw new RuntimeException("Error reading GeoLite2 database", e);
	        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetCityByIp";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
