// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datastore.proxies;

public class Lecture implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject lectureMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataStore.Lecture";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LectureName("LectureName"),
		CourseName("CourseName"),
		SchoolType("SchoolType");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Lecture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Lecture(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject lectureMendixObject)
	{
		if (lectureMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, lectureMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.lectureMendixObject = lectureMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static datastore.proxies.Lecture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datastore.proxies.Lecture(context, mendixObject);
	}

	public static datastore.proxies.Lecture load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datastore.proxies.Lecture.initialize(context, mendixObject);
	}

	/**
	 * @return value of LectureName
	 */
	public final java.lang.String getLectureName()
	{
		return getLectureName(getContext());
	}

	/**
	 * @param context
	 * @return value of LectureName
	 */
	public final java.lang.String getLectureName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LectureName.toString());
	}

	/**
	 * Set value of LectureName
	 * @param lecturename
	 */
	public final void setLectureName(java.lang.String lecturename)
	{
		setLectureName(getContext(), lecturename);
	}

	/**
	 * Set value of LectureName
	 * @param context
	 * @param lecturename
	 */
	public final void setLectureName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lecturename)
	{
		getMendixObject().setValue(context, MemberNames.LectureName.toString(), lecturename);
	}

	/**
	 * @return value of CourseName
	 */
	public final java.lang.String getCourseName()
	{
		return getCourseName(getContext());
	}

	/**
	 * @param context
	 * @return value of CourseName
	 */
	public final java.lang.String getCourseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CourseName.toString());
	}

	/**
	 * Set value of CourseName
	 * @param coursename
	 */
	public final void setCourseName(java.lang.String coursename)
	{
		setCourseName(getContext(), coursename);
	}

	/**
	 * Set value of CourseName
	 * @param context
	 * @param coursename
	 */
	public final void setCourseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String coursename)
	{
		getMendixObject().setValue(context, MemberNames.CourseName.toString(), coursename);
	}

	/**
	 * @return value of SchoolType
	 */
	public final java.lang.String getSchoolType()
	{
		return getSchoolType(getContext());
	}

	/**
	 * @param context
	 * @return value of SchoolType
	 */
	public final java.lang.String getSchoolType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SchoolType.toString());
	}

	/**
	 * Set value of SchoolType
	 * @param schooltype
	 */
	public final void setSchoolType(java.lang.String schooltype)
	{
		setSchoolType(getContext(), schooltype);
	}

	/**
	 * Set value of SchoolType
	 * @param context
	 * @param schooltype
	 */
	public final void setSchoolType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String schooltype)
	{
		getMendixObject().setValue(context, MemberNames.SchoolType.toString(), schooltype);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return lectureMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datastore.proxies.Lecture that = (datastore.proxies.Lecture) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
