// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datastore.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the DataStore module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Lecture_FromOQLBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.ACT_Lecture_FromOQL");
		return builder;
	}

	public static void aCT_Lecture_FromOQL(IContext context)
	{
		aCT_Lecture_FromOQLBuilder().execute(context);
	}
}
