// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datastore.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the DataStore module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BuilderTest_GetByUserBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.ACT_BuilderTest_GetByUser");
		return builder;
	}

	public static void aCT_BuilderTest_GetByUser(IContext context)
	{
		aCT_BuilderTest_GetByUserBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Lecture_FromOQL_V1Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.ACT_Lecture_FromOQL_V1");
		return builder;
	}

	public static void aCT_Lecture_FromOQL_V1(IContext context)
	{
		aCT_Lecture_FromOQL_V1Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Lecture_FromOQL_V2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.ACT_Lecture_FromOQL_V2");
		return builder;
	}

	public static void aCT_Lecture_FromOQL_V2(IContext context)
	{
		aCT_Lecture_FromOQL_V2Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder calculateMicroflowExecutionTimeBuilder(
		java.util.Date _startDate
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.CalculateMicroflowExecutionTime");
		builder = builder.withParam("StartDate", _startDate);
		return builder;
	}

	public static java.math.BigDecimal calculateMicroflowExecutionTime(
		IContext context,
		java.util.Date _startDate
	)
	{
		Object result = calculateMicroflowExecutionTimeBuilder(
				_startDate
			)
			.execute(context);
		return (java.math.BigDecimal) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cNV_CourseNameBuilder(
		java.lang.String _courseName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.CNV_CourseName");
		builder = builder.withParam("CourseName", _courseName);
		return builder;
	}

	public static java.lang.String cNV_CourseName(
		IContext context,
		java.lang.String _courseName
	)
	{
		Object result = cNV_CourseNameBuilder(
				_courseName
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cNV_LectureNameBuilder(
		java.lang.String _lectureName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.CNV_LectureName");
		builder = builder.withParam("LectureName", _lectureName);
		return builder;
	}

	public static java.lang.String cNV_LectureName(
		IContext context,
		java.lang.String _lectureName
	)
	{
		Object result = cNV_LectureNameBuilder(
				_lectureName
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cNV_SchoolTypeBuilder(
		java.lang.String _schoolType
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.CNV_SchoolType");
		builder = builder.withParam("SchoolType", _schoolType);
		return builder;
	}

	public static java.lang.String cNV_SchoolType(
		IContext context,
		java.lang.String _schoolType
	)
	{
		Object result = cNV_SchoolTypeBuilder(
				_schoolType
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getMicroflowStartTimeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.GetMicroflowStartTime");
		return builder;
	}

	public static java.util.Date getMicroflowStartTime(IContext context)
	{
		Object result = getMicroflowStartTimeBuilder().execute(context);
		return (java.util.Date) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder logMicroflowExecutionTimeBuilder(
		java.util.Date _startDate,
		java.lang.String _microflowName
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.LogMicroflowExecutionTime");
		builder = builder.withParam("StartDate", _startDate);
		builder = builder.withParam("MicroflowName", _microflowName);
		return builder;
	}

	public static void logMicroflowExecutionTime(
		IContext context,
		java.util.Date _startDate,
		java.lang.String _microflowName
	)
	{
		logMicroflowExecutionTimeBuilder(
				_startDate,
				_microflowName
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_GetBuilderTests_ByUserBuilder(
		java.lang.Long _amount,
		administration.proxies.Account _account
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("DataStore.SUB_GetBuilderTests_ByUser");
		builder = builder.withParam("Amount", _amount);
		builder = builder.withParam("Account", _account);
		return builder;
	}

	public static java.lang.String sUB_GetBuilderTests_ByUser(
		IContext context,
		java.lang.Long _amount,
		administration.proxies.Account _account
	)
	{
		Object result = sUB_GetBuilderTests_ByUserBuilder(
				_amount,
				_account
			)
			.execute(context);
		return (java.lang.String) result;
	}
}
