define(["big.js"], (__WEBPACK_EXTERNAL_MODULE_big_js__) => { return /******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/builder/actions/JS_Fix_OnQuestionBodyChange.js":
/*!****************************************************************************************************************************!*\
  !*** ../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/builder/actions/JS_Fix_OnQuestionBodyChange.js ***!
  \****************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_Fix_OnQuestionBodyChange: () => (/* binding */ JS_Fix_OnQuestionBodyChange)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} question
 * @returns {Promise.<void>}
 */
async function JS_Fix_OnQuestionBodyChange(question) {
  // BEGIN USER CODE

  function isWrapped(strHTML) {
    return strHTML.startsWith("<p>") && strHTML.endsWith("</p>");
  }
  function wrap(strHTML) {
    return "<p>" + strHTML + "</p>";
  }
  function placeCaretAtEnd(el) {
    el.focus();
    if (typeof window.getSelection != "undefined" && typeof document.createRange != "undefined") {
      const range = document.createRange();
      range.selectNodeContents(el);
      range.collapse(false);
      const sel = window.getSelection();
      sel.removeAllRanges();
      sel.addRange(range);
    } else if (typeof document.body.createTextRange != "undefined") {
      const textRange = document.body.createTextRange();
      textRange.moveToElementText(el);
      textRange.collapse(false);
      textRange.select();
    }
  }
  const questionBody = question.get("QuestionBody");
  const textEditor = document.getElementsByClassName("w-e-text")[0];
  const wrapped = isWrapped(questionBody);
  if (wrapped) {
    return;
  }
  textEditor.innerHTML = wrap(questionBody);
  placeCaretAtEnd(textEditor);

  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/builder/actions/JS_Fix_OnQuestionChange.js":
/*!************************************************************************************************************************!*\
  !*** ../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/builder/actions/JS_Fix_OnQuestionChange.js ***!
  \************************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   JS_Fix_OnQuestionChange: () => (/* binding */ JS_Fix_OnQuestionChange)
/* harmony export */ });
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! mx-global */ "?391f");
/* harmony import */ var mx_global__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(mx_global__WEBPACK_IMPORTED_MODULE_0__);
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_1__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.



// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} question
 * @returns {Promise.<void>}
 */
async function JS_Fix_OnQuestionChange(question) {
  // BEGIN USER CODE

  function isWrapped(strHTML) {
    return strHTML.startsWith("<p>") && strHTML.endsWith("</p>");
  }
  function wrap(strHTML) {
    return "<p>" + strHTML + "</p>";
  }
  const questionBody = question.get("QuestionBody");
  const textEditor = document.getElementsByClassName("w-e-text")[0];
  const wrapped = isWrapped(questionBody);
  if (wrapped) {
    return textEditor.innerHTML = questionBody;
  }
  textEditor.innerHTML = wrap(questionBody);

  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/nanoflowcommons/actions/HideProgress.js":
/*!*********************************************************************************************************************!*\
  !*** ../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/nanoflowcommons/actions/HideProgress.js ***!
  \*********************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   HideProgress: () => (/* binding */ HideProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.


// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Hides default progress bar
 * @param {Big} identifier - Identifier of ui which should be hidden. This param is required
 * @returns {Promise.<void>}
 */
async function HideProgress(identifier) {
  // BEGIN USER CODE
  if (identifier == null) {
    return Promise.reject(new Error("Input parameter 'Identifier' is required"));
  }
  mx.ui.hideProgress(Number(identifier));
  return Promise.resolve();
  // END USER CODE
}

/***/ }),

/***/ "../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/nanoflowcommons/actions/ShowProgress.js":
/*!*********************************************************************************************************************!*\
  !*** ../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/nanoflowcommons/actions/ShowProgress.js ***!
  \*********************************************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   ShowProgress: () => (/* binding */ ShowProgress)
/* harmony export */ });
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! big.js */ "big.js");
/* harmony import */ var big_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(big_js__WEBPACK_IMPORTED_MODULE_0__);
// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.


// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Shows default progress bar
 * @param {string} message - The text to show while loading.
 * @param {boolean} blocking - Block the user interface immediately.
 * @returns {Promise.<Big>}
 */
async function ShowProgress(message, blocking) {
  // BEGIN USER CODE
  const id = mx.ui.showProgress(message, blocking);
  if (id !== undefined) {
    return Promise.resolve(new big_js__WEBPACK_IMPORTED_MODULE_0__.Big(id));
  }
  return Promise.reject(new Error("Could not open the loading dialog"));
  // END USER CODE
}

/***/ }),

/***/ "big.js":
/*!*************************!*\
  !*** external "big.js" ***!
  \*************************/
/***/ ((module) => {

"use strict";
module.exports = __WEBPACK_EXTERNAL_MODULE_big_js__;

/***/ }),

/***/ "?391f":
/*!**********************************!*\
  !*** mx-global (ignored module) ***!
  \**********************************/
/***/ (() => {

/* empty */

/***/ })

/******/ 	});
/************************************************************************/
/******/ 	// The module cache
/******/ 	var __webpack_module_cache__ = {};
/******/ 	
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/ 		// Check if module is in cache
/******/ 		var cachedModule = __webpack_module_cache__[moduleId];
/******/ 		if (cachedModule !== undefined) {
/******/ 			return cachedModule.exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = __webpack_module_cache__[moduleId] = {
/******/ 			// no module.id needed
/******/ 			// no module.loaded needed
/******/ 			exports: {}
/******/ 		};
/******/ 	
/******/ 		// Execute the module function
/******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
/******/ 	
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/ 	
/************************************************************************/
/******/ 	/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/define property getters */
/******/ 	(() => {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = (exports, definition) => {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/hasOwnProperty shorthand */
/******/ 	(() => {
/******/ 		__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ 	})();
/******/ 	
/******/ 	/* webpack/runtime/make namespace object */
/******/ 	(() => {
/******/ 		// define __esModule on exports
/******/ 		__webpack_require__.r = (exports) => {
/******/ 			if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 				Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 			}
/******/ 			Object.defineProperty(exports, '__esModule', { value: true });
/******/ 		};
/******/ 	})();
/******/ 	
/************************************************************************/
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
/*!****************************************************************************************!*\
  !*** ../../../../../../Users/TKA/Documents/Mendix/QuizApp/deployment/tmp/jsactions.js ***!
  \****************************************************************************************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Builder$JS_Fix_OnQuestionBodyChange: () => (/* binding */ Builder$JS_Fix_OnQuestionBodyChange),
/* harmony export */   Builder$JS_Fix_OnQuestionChange: () => (/* binding */ Builder$JS_Fix_OnQuestionChange),
/* harmony export */   NanoflowCommons$HideProgress: () => (/* binding */ NanoflowCommons$HideProgress),
/* harmony export */   NanoflowCommons$ShowProgress: () => (/* binding */ NanoflowCommons$ShowProgress)
/* harmony export */ });
const NanoflowCommons$ShowProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/nanoflowcommons/actions/ShowProgress */ "../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/nanoflowcommons/actions/ShowProgress.js"))).ShowProgress;
const NanoflowCommons$HideProgress = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/nanoflowcommons/actions/HideProgress */ "../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/nanoflowcommons/actions/HideProgress.js"))).HideProgress;
const Builder$JS_Fix_OnQuestionChange = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/builder/actions/JS_Fix_OnQuestionChange */ "../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/builder/actions/JS_Fix_OnQuestionChange.js"))).JS_Fix_OnQuestionChange;
const Builder$JS_Fix_OnQuestionBodyChange = async () => (await Promise.resolve(/*! import() */).then(__webpack_require__.bind(__webpack_require__, /*! ../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/builder/actions/JS_Fix_OnQuestionBodyChange */ "../../../../../../Users/TKA/Documents/Mendix/QuizApp/javascriptsource/builder/actions/JS_Fix_OnQuestionBodyChange.js"))).JS_Fix_OnQuestionBodyChange;
})();

/******/ 	return __webpack_exports__;
/******/ })()
;
});;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoianNhY3Rpb25zLmpzIiwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ21CO0FBQ1U7O0FBRTdCO0FBQ0E7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlQywyQkFBMkIsQ0FBQ0MsUUFBUSxFQUFFO0VBQzNEOztFQUVBLFNBQVNDLFNBQVMsQ0FBQ0MsT0FBTyxFQUFFO0lBQzNCLE9BQU9BLE9BQU8sQ0FBQ0MsVUFBVSxDQUFDLEtBQUssQ0FBQyxJQUFJRCxPQUFPLENBQUNFLFFBQVEsQ0FBQyxNQUFNLENBQUM7RUFFN0Q7RUFDQSxTQUFTQyxJQUFJLENBQUNILE9BQU8sRUFBRTtJQUN0QixPQUFPLEtBQUssR0FBR0EsT0FBTyxHQUFHLE1BQU07RUFDaEM7RUFFQSxTQUFTSSxlQUFlLENBQUNDLEVBQUUsRUFBRTtJQUM1QkEsRUFBRSxDQUFDQyxLQUFLLEVBQUU7SUFDVixJQUFJLE9BQU9DLE1BQU0sQ0FBQ0MsWUFBWSxJQUFJLFdBQVcsSUFBSSxPQUFPQyxRQUFRLENBQUNDLFdBQVcsSUFBSSxXQUFXLEVBQUU7TUFDNUYsTUFBTUMsS0FBSyxHQUFHRixRQUFRLENBQUNDLFdBQVcsRUFBRTtNQUNwQ0MsS0FBSyxDQUFDQyxrQkFBa0IsQ0FBQ1AsRUFBRSxDQUFDO01BQzVCTSxLQUFLLENBQUNFLFFBQVEsQ0FBQyxLQUFLLENBQUM7TUFDckIsTUFBTUMsR0FBRyxHQUFHUCxNQUFNLENBQUNDLFlBQVksRUFBRTtNQUNqQ00sR0FBRyxDQUFDQyxlQUFlLEVBQUU7TUFDckJELEdBQUcsQ0FBQ0UsUUFBUSxDQUFDTCxLQUFLLENBQUM7SUFDcEIsQ0FBQyxNQUFNLElBQUksT0FBT0YsUUFBUSxDQUFDUSxJQUFJLENBQUNDLGVBQWUsSUFBSSxXQUFXLEVBQUU7TUFDL0QsTUFBTUMsU0FBUyxHQUFHVixRQUFRLENBQUNRLElBQUksQ0FBQ0MsZUFBZSxFQUFFO01BQ2pEQyxTQUFTLENBQUNDLGlCQUFpQixDQUFDZixFQUFFLENBQUM7TUFDL0JjLFNBQVMsQ0FBQ04sUUFBUSxDQUFDLEtBQUssQ0FBQztNQUN6Qk0sU0FBUyxDQUFDRSxNQUFNLEVBQUU7SUFDbkI7RUFDRDtFQUVBLE1BQU1DLFlBQVksR0FBR3hCLFFBQVEsQ0FBQ3lCLEdBQUcsQ0FBQyxjQUFjLENBQUM7RUFDakQsTUFBTUMsVUFBVSxHQUFHZixRQUFRLENBQUNnQixzQkFBc0IsQ0FBQyxVQUFVLENBQUMsQ0FBQyxDQUFDLENBQUM7RUFDakUsTUFBTUMsT0FBTyxHQUFHM0IsU0FBUyxDQUFDdUIsWUFBWSxDQUFDO0VBRXZDLElBQUlJLE9BQU8sRUFBRTtJQUNaO0VBQ0Q7RUFFQUYsVUFBVSxDQUFDRyxTQUFTLEdBQUd4QixJQUFJLENBQUNtQixZQUFZLENBQUM7RUFDekNsQixlQUFlLENBQUNvQixVQUFVLENBQUM7O0VBRTNCO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUN6REE7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDbUI7QUFDVTs7QUFFN0I7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNPLGVBQWVJLHVCQUF1QixDQUFDOUIsUUFBUSxFQUFFO0VBQ3ZEOztFQUVBLFNBQVNDLFNBQVMsQ0FBQ0MsT0FBTyxFQUFFO0lBQzNCLE9BQU9BLE9BQU8sQ0FBQ0MsVUFBVSxDQUFDLEtBQUssQ0FBQyxJQUFJRCxPQUFPLENBQUNFLFFBQVEsQ0FBQyxNQUFNLENBQUM7RUFFN0Q7RUFFQSxTQUFTQyxJQUFJLENBQUNILE9BQU8sRUFBRTtJQUN0QixPQUFPLEtBQUssR0FBR0EsT0FBTyxHQUFHLE1BQU07RUFDaEM7RUFFQSxNQUFNc0IsWUFBWSxHQUFHeEIsUUFBUSxDQUFDeUIsR0FBRyxDQUFDLGNBQWMsQ0FBQztFQUNqRCxNQUFNQyxVQUFVLEdBQUdmLFFBQVEsQ0FBQ2dCLHNCQUFzQixDQUFDLFVBQVUsQ0FBQyxDQUFDLENBQUMsQ0FBQztFQUNqRSxNQUFNQyxPQUFPLEdBQUczQixTQUFTLENBQUN1QixZQUFZLENBQUM7RUFFdkMsSUFBSUksT0FBTyxFQUFFO0lBQ1osT0FBT0YsVUFBVSxDQUFDRyxTQUFTLEdBQUdMLFlBQVk7RUFDM0M7RUFHQUUsVUFBVSxDQUFDRyxTQUFTLEdBQUd4QixJQUFJLENBQUNtQixZQUFZLENBQUM7O0VBRXpDO0FBQ0Q7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDekNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQzZCOztBQUU3QjtBQUNBOztBQUVBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlTyxZQUFZLENBQUNDLFVBQVUsRUFBRTtFQUM5QztFQUNHLElBQUlBLFVBQVUsSUFBSSxJQUFJLEVBQUU7SUFDcEIsT0FBT0MsT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLDBDQUEwQyxDQUFDLENBQUM7RUFDaEY7RUFDQUMsRUFBRSxDQUFDQyxFQUFFLENBQUNDLFlBQVksQ0FBQ0MsTUFBTSxDQUFDUCxVQUFVLENBQUMsQ0FBQztFQUN0QyxPQUFPQyxPQUFPLENBQUNPLE9BQU8sRUFBRTtFQUMzQjtBQUNEOzs7Ozs7Ozs7Ozs7Ozs7OztBQ3pCQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUM2Qjs7QUFFN0I7QUFDQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDTyxlQUFlQyxZQUFZLENBQUNDLE9BQU8sRUFBRUMsUUFBUSxFQUFFO0VBQ3JEO0VBQ0csTUFBTUMsRUFBRSxHQUFHUixFQUFFLENBQUNDLEVBQUUsQ0FBQ1EsWUFBWSxDQUFDSCxPQUFPLEVBQUVDLFFBQVEsQ0FBQztFQUNoRCxJQUFJQyxFQUFFLEtBQUtFLFNBQVMsRUFBRTtJQUNsQixPQUFPYixPQUFPLENBQUNPLE9BQU8sQ0FBQyxJQUFJMUMsdUNBQUcsQ0FBQzhDLEVBQUUsQ0FBQyxDQUFDO0VBQ3ZDO0VBQ0EsT0FBT1gsT0FBTyxDQUFDQyxNQUFNLENBQUMsSUFBSUMsS0FBSyxDQUFDLG1DQUFtQyxDQUFDLENBQUM7RUFDeEU7QUFDRDs7Ozs7Ozs7Ozs7QUMxQkE7Ozs7Ozs7Ozs7QUNBQTs7Ozs7O1VDQUE7VUFDQTs7VUFFQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTtVQUNBO1VBQ0E7VUFDQTs7VUFFQTtVQUNBOztVQUVBO1VBQ0E7VUFDQTs7Ozs7V0N0QkE7V0FDQTtXQUNBO1dBQ0E7V0FDQTtXQUNBLGlDQUFpQyxXQUFXO1dBQzVDO1dBQ0E7Ozs7O1dDUEE7V0FDQTtXQUNBO1dBQ0E7V0FDQSx5Q0FBeUMsd0NBQXdDO1dBQ2pGO1dBQ0E7V0FDQTs7Ozs7V0NQQTs7Ozs7V0NBQTtXQUNBO1dBQ0E7V0FDQSx1REFBdUQsaUJBQWlCO1dBQ3hFO1dBQ0EsZ0RBQWdELGFBQWE7V0FDN0Q7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ05PLE1BQU1ZLDRCQUE0QixHQUFHLFlBQVksQ0FBQyxNQUFNLHVUQUFxRyxFQUFFTixZQUFZO0FBQzNLLE1BQU1PLDRCQUE0QixHQUFHLFlBQVksQ0FBQyxNQUFNLHVUQUFxRyxFQUFFakIsWUFBWTtBQUMzSyxNQUFNa0IsK0JBQStCLEdBQUcsWUFBWSxDQUFDLE1BQU0sNlRBQXdHLEVBQUVuQix1QkFBdUI7QUFDNUwsTUFBTW9CLG1DQUFtQyxHQUFHLFlBQVksQ0FBQyxNQUFNLHFVQUE0RyxFQUFFbkQsMkJBQTJCLEMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi4vLi4vLi4vLi4vLi4vLi4vVXNlcnMvVEtBL0RvY3VtZW50cy9NZW5kaXgvUXVpekFwcC9qYXZhc2NyaXB0c291cmNlL2J1aWxkZXIvYWN0aW9ucy9KU19GaXhfT25RdWVzdGlvbkJvZHlDaGFuZ2UuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL1RLQS9Eb2N1bWVudHMvTWVuZGl4L1F1aXpBcHAvamF2YXNjcmlwdHNvdXJjZS9idWlsZGVyL2FjdGlvbnMvSlNfRml4X09uUXVlc3Rpb25DaGFuZ2UuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL1RLQS9Eb2N1bWVudHMvTWVuZGl4L1F1aXpBcHAvamF2YXNjcmlwdHNvdXJjZS9uYW5vZmxvd2NvbW1vbnMvYWN0aW9ucy9IaWRlUHJvZ3Jlc3MuanMiLCJ3ZWJwYWNrOi8vLy4uLy4uLy4uLy4uLy4uLy4uL1VzZXJzL1RLQS9Eb2N1bWVudHMvTWVuZGl4L1F1aXpBcHAvamF2YXNjcmlwdHNvdXJjZS9uYW5vZmxvd2NvbW1vbnMvYWN0aW9ucy9TaG93UHJvZ3Jlc3MuanMiLCJ3ZWJwYWNrOi8vL2V4dGVybmFsIGFtZCBcImJpZy5qc1wiIiwid2VicGFjazovLy9teC1nbG9iYWwiLCJ3ZWJwYWNrOi8vL3dlYnBhY2svYm9vdHN0cmFwIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvY29tcGF0IGdldCBkZWZhdWx0IGV4cG9ydCIsIndlYnBhY2s6Ly8vd2VicGFjay9ydW50aW1lL2RlZmluZSBwcm9wZXJ0eSBnZXR0ZXJzIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvaGFzT3duUHJvcGVydHkgc2hvcnRoYW5kIiwid2VicGFjazovLy93ZWJwYWNrL3J1bnRpbWUvbWFrZSBuYW1lc3BhY2Ugb2JqZWN0Iiwid2VicGFjazovLy8uLi8uLi8uLi8uLi8uLi8uLi9Vc2Vycy9US0EvRG9jdW1lbnRzL01lbmRpeC9RdWl6QXBwL2RlcGxveW1lbnQvdG1wL2pzYWN0aW9ucy5qcyJdLCJzb3VyY2VzQ29udGVudCI6WyIvLyBUaGlzIGZpbGUgd2FzIGdlbmVyYXRlZCBieSBNZW5kaXggU3R1ZGlvIFByby5cclxuLy9cclxuLy8gV0FSTklORzogT25seSB0aGUgZm9sbG93aW5nIGNvZGUgd2lsbCBiZSByZXRhaW5lZCB3aGVuIGFjdGlvbnMgYXJlIHJlZ2VuZXJhdGVkOlxyXG4vLyAtIHRoZSBpbXBvcnQgbGlzdFxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gVVNFUiBDT0RFIGFuZCBFTkQgVVNFUiBDT0RFXHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBFWFRSQSBDT0RFIGFuZCBFTkQgRVhUUkEgQ09ERVxyXG4vLyBPdGhlciBjb2RlIHlvdSB3cml0ZSB3aWxsIGJlIGxvc3QgdGhlIG5leHQgdGltZSB5b3UgZGVwbG95IHRoZSBwcm9qZWN0LlxyXG5pbXBvcnQgXCJteC1nbG9iYWxcIjtcclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIEBwYXJhbSB7TXhPYmplY3R9IHF1ZXN0aW9uXHJcbiAqIEByZXR1cm5zIHtQcm9taXNlLjx2b2lkPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBKU19GaXhfT25RdWVzdGlvbkJvZHlDaGFuZ2UocXVlc3Rpb24pIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuXHRcclxuXHRmdW5jdGlvbiBpc1dyYXBwZWQoc3RySFRNTCkge1xyXG5cdFx0cmV0dXJuIHN0ckhUTUwuc3RhcnRzV2l0aChcIjxwPlwiKSAmJiBzdHJIVE1MLmVuZHNXaXRoKFwiPC9wPlwiKTtcclxuXHJcblx0fVxyXG5cdGZ1bmN0aW9uIHdyYXAoc3RySFRNTCkge1xyXG5cdFx0cmV0dXJuIFwiPHA+XCIgKyBzdHJIVE1MICsgXCI8L3A+XCI7XHJcblx0fVxyXG5cclxuXHRmdW5jdGlvbiBwbGFjZUNhcmV0QXRFbmQoZWwpIHtcclxuXHRcdGVsLmZvY3VzKCk7XHJcblx0XHRpZiAodHlwZW9mIHdpbmRvdy5nZXRTZWxlY3Rpb24gIT0gXCJ1bmRlZmluZWRcIiAmJiB0eXBlb2YgZG9jdW1lbnQuY3JlYXRlUmFuZ2UgIT0gXCJ1bmRlZmluZWRcIikge1xyXG5cdFx0XHRjb25zdCByYW5nZSA9IGRvY3VtZW50LmNyZWF0ZVJhbmdlKCk7XHJcblx0XHRcdHJhbmdlLnNlbGVjdE5vZGVDb250ZW50cyhlbCk7XHJcblx0XHRcdHJhbmdlLmNvbGxhcHNlKGZhbHNlKTtcclxuXHRcdFx0Y29uc3Qgc2VsID0gd2luZG93LmdldFNlbGVjdGlvbigpO1xyXG5cdFx0XHRzZWwucmVtb3ZlQWxsUmFuZ2VzKCk7XHJcblx0XHRcdHNlbC5hZGRSYW5nZShyYW5nZSk7XHJcblx0XHR9IGVsc2UgaWYgKHR5cGVvZiBkb2N1bWVudC5ib2R5LmNyZWF0ZVRleHRSYW5nZSAhPSBcInVuZGVmaW5lZFwiKSB7XHJcblx0XHRcdGNvbnN0IHRleHRSYW5nZSA9IGRvY3VtZW50LmJvZHkuY3JlYXRlVGV4dFJhbmdlKCk7XHJcblx0XHRcdHRleHRSYW5nZS5tb3ZlVG9FbGVtZW50VGV4dChlbCk7XHJcblx0XHRcdHRleHRSYW5nZS5jb2xsYXBzZShmYWxzZSk7XHJcblx0XHRcdHRleHRSYW5nZS5zZWxlY3QoKTtcclxuXHRcdH1cclxuXHR9XHJcblxyXG5cdGNvbnN0IHF1ZXN0aW9uQm9keSA9IHF1ZXN0aW9uLmdldChcIlF1ZXN0aW9uQm9keVwiKTtcclxuXHRjb25zdCB0ZXh0RWRpdG9yID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZShcInctZS10ZXh0XCIpWzBdO1xyXG5cdGNvbnN0IHdyYXBwZWQgPSBpc1dyYXBwZWQocXVlc3Rpb25Cb2R5KTtcclxuXHRcclxuXHRpZiAod3JhcHBlZCkge1xyXG5cdFx0cmV0dXJuO1xyXG5cdH1cclxuXHJcblx0dGV4dEVkaXRvci5pbm5lckhUTUwgPSB3cmFwKHF1ZXN0aW9uQm9keSk7XHJcblx0cGxhY2VDYXJldEF0RW5kKHRleHRFZGl0b3IpO1xyXG5cclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IFwibXgtZ2xvYmFsXCI7XHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBAcGFyYW0ge014T2JqZWN0fSBxdWVzdGlvblxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gSlNfRml4X09uUXVlc3Rpb25DaGFuZ2UocXVlc3Rpb24pIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuXHJcblx0ZnVuY3Rpb24gaXNXcmFwcGVkKHN0ckhUTUwpIHtcclxuXHRcdHJldHVybiBzdHJIVE1MLnN0YXJ0c1dpdGgoXCI8cD5cIikgJiYgc3RySFRNTC5lbmRzV2l0aChcIjwvcD5cIik7XHJcblxyXG5cdH1cclxuXHJcblx0ZnVuY3Rpb24gd3JhcChzdHJIVE1MKSB7XHJcblx0XHRyZXR1cm4gXCI8cD5cIiArIHN0ckhUTUwgKyBcIjwvcD5cIjtcclxuXHR9XHJcblxyXG5cdGNvbnN0IHF1ZXN0aW9uQm9keSA9IHF1ZXN0aW9uLmdldChcIlF1ZXN0aW9uQm9keVwiKTtcclxuXHRjb25zdCB0ZXh0RWRpdG9yID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZShcInctZS10ZXh0XCIpWzBdO1xyXG5cdGNvbnN0IHdyYXBwZWQgPSBpc1dyYXBwZWQocXVlc3Rpb25Cb2R5KTtcclxuXHJcblx0aWYgKHdyYXBwZWQpIHtcclxuXHRcdHJldHVybiB0ZXh0RWRpdG9yLmlubmVySFRNTCA9IHF1ZXN0aW9uQm9keTtcclxuXHR9XHJcblxyXG5cclxuXHR0ZXh0RWRpdG9yLmlubmVySFRNTCA9IHdyYXAocXVlc3Rpb25Cb2R5KTtcclxuXHJcblx0Ly8gRU5EIFVTRVIgQ09ERVxyXG59XHJcbiIsIi8vIFRoaXMgZmlsZSB3YXMgZ2VuZXJhdGVkIGJ5IE1lbmRpeCBTdHVkaW8gUHJvLlxyXG4vL1xyXG4vLyBXQVJOSU5HOiBPbmx5IHRoZSBmb2xsb3dpbmcgY29kZSB3aWxsIGJlIHJldGFpbmVkIHdoZW4gYWN0aW9ucyBhcmUgcmVnZW5lcmF0ZWQ6XHJcbi8vIC0gdGhlIGltcG9ydCBsaXN0XHJcbi8vIC0gdGhlIGNvZGUgYmV0d2VlbiBCRUdJTiBVU0VSIENPREUgYW5kIEVORCBVU0VSIENPREVcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIEVYVFJBIENPREUgYW5kIEVORCBFWFRSQSBDT0RFXHJcbi8vIE90aGVyIGNvZGUgeW91IHdyaXRlIHdpbGwgYmUgbG9zdCB0aGUgbmV4dCB0aW1lIHlvdSBkZXBsb3kgdGhlIHByb2plY3QuXHJcbmltcG9ydCB7IEJpZyB9IGZyb20gXCJiaWcuanNcIjtcclxuXHJcbi8vIEJFR0lOIEVYVFJBIENPREVcclxuLy8gRU5EIEVYVFJBIENPREVcclxuXHJcbi8qKlxyXG4gKiBIaWRlcyBkZWZhdWx0IHByb2dyZXNzIGJhclxyXG4gKiBAcGFyYW0ge0JpZ30gaWRlbnRpZmllciAtIElkZW50aWZpZXIgb2YgdWkgd2hpY2ggc2hvdWxkIGJlIGhpZGRlbi4gVGhpcyBwYXJhbSBpcyByZXF1aXJlZFxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48dm9pZD59XHJcbiAqL1xyXG5leHBvcnQgYXN5bmMgZnVuY3Rpb24gSGlkZVByb2dyZXNzKGlkZW50aWZpZXIpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuICAgIGlmIChpZGVudGlmaWVyID09IG51bGwpIHtcclxuICAgICAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwiSW5wdXQgcGFyYW1ldGVyICdJZGVudGlmaWVyJyBpcyByZXF1aXJlZFwiKSk7XHJcbiAgICB9XHJcbiAgICBteC51aS5oaWRlUHJvZ3Jlc3MoTnVtYmVyKGlkZW50aWZpZXIpKTtcclxuICAgIHJldHVybiBQcm9taXNlLnJlc29sdmUoKTtcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwiLy8gVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgTWVuZGl4IFN0dWRpbyBQcm8uXHJcbi8vXHJcbi8vIFdBUk5JTkc6IE9ubHkgdGhlIGZvbGxvd2luZyBjb2RlIHdpbGwgYmUgcmV0YWluZWQgd2hlbiBhY3Rpb25zIGFyZSByZWdlbmVyYXRlZDpcclxuLy8gLSB0aGUgaW1wb3J0IGxpc3RcclxuLy8gLSB0aGUgY29kZSBiZXR3ZWVuIEJFR0lOIFVTRVIgQ09ERSBhbmQgRU5EIFVTRVIgQ09ERVxyXG4vLyAtIHRoZSBjb2RlIGJldHdlZW4gQkVHSU4gRVhUUkEgQ09ERSBhbmQgRU5EIEVYVFJBIENPREVcclxuLy8gT3RoZXIgY29kZSB5b3Ugd3JpdGUgd2lsbCBiZSBsb3N0IHRoZSBuZXh0IHRpbWUgeW91IGRlcGxveSB0aGUgcHJvamVjdC5cclxuaW1wb3J0IHsgQmlnIH0gZnJvbSBcImJpZy5qc1wiO1xyXG5cclxuLy8gQkVHSU4gRVhUUkEgQ09ERVxyXG4vLyBFTkQgRVhUUkEgQ09ERVxyXG5cclxuLyoqXHJcbiAqIFNob3dzIGRlZmF1bHQgcHJvZ3Jlc3MgYmFyXHJcbiAqIEBwYXJhbSB7c3RyaW5nfSBtZXNzYWdlIC0gVGhlIHRleHQgdG8gc2hvdyB3aGlsZSBsb2FkaW5nLlxyXG4gKiBAcGFyYW0ge2Jvb2xlYW59IGJsb2NraW5nIC0gQmxvY2sgdGhlIHVzZXIgaW50ZXJmYWNlIGltbWVkaWF0ZWx5LlxyXG4gKiBAcmV0dXJucyB7UHJvbWlzZS48QmlnPn1cclxuICovXHJcbmV4cG9ydCBhc3luYyBmdW5jdGlvbiBTaG93UHJvZ3Jlc3MobWVzc2FnZSwgYmxvY2tpbmcpIHtcclxuXHQvLyBCRUdJTiBVU0VSIENPREVcclxuICAgIGNvbnN0IGlkID0gbXgudWkuc2hvd1Byb2dyZXNzKG1lc3NhZ2UsIGJsb2NraW5nKTtcclxuICAgIGlmIChpZCAhPT0gdW5kZWZpbmVkKSB7XHJcbiAgICAgICAgcmV0dXJuIFByb21pc2UucmVzb2x2ZShuZXcgQmlnKGlkKSk7XHJcbiAgICB9XHJcbiAgICByZXR1cm4gUHJvbWlzZS5yZWplY3QobmV3IEVycm9yKFwiQ291bGQgbm90IG9wZW4gdGhlIGxvYWRpbmcgZGlhbG9nXCIpKTtcclxuXHQvLyBFTkQgVVNFUiBDT0RFXHJcbn1cclxuIiwibW9kdWxlLmV4cG9ydHMgPSBfX1dFQlBBQ0tfRVhURVJOQUxfTU9EVUxFX2JpZ19qc19fOyIsIi8qIGVtcHR5ICovIiwiLy8gVGhlIG1vZHVsZSBjYWNoZVxudmFyIF9fd2VicGFja19tb2R1bGVfY2FjaGVfXyA9IHt9O1xuXG4vLyBUaGUgcmVxdWlyZSBmdW5jdGlvblxuZnVuY3Rpb24gX193ZWJwYWNrX3JlcXVpcmVfXyhtb2R1bGVJZCkge1xuXHQvLyBDaGVjayBpZiBtb2R1bGUgaXMgaW4gY2FjaGVcblx0dmFyIGNhY2hlZE1vZHVsZSA9IF9fd2VicGFja19tb2R1bGVfY2FjaGVfX1ttb2R1bGVJZF07XG5cdGlmIChjYWNoZWRNb2R1bGUgIT09IHVuZGVmaW5lZCkge1xuXHRcdHJldHVybiBjYWNoZWRNb2R1bGUuZXhwb3J0cztcblx0fVxuXHQvLyBDcmVhdGUgYSBuZXcgbW9kdWxlIChhbmQgcHV0IGl0IGludG8gdGhlIGNhY2hlKVxuXHR2YXIgbW9kdWxlID0gX193ZWJwYWNrX21vZHVsZV9jYWNoZV9fW21vZHVsZUlkXSA9IHtcblx0XHQvLyBubyBtb2R1bGUuaWQgbmVlZGVkXG5cdFx0Ly8gbm8gbW9kdWxlLmxvYWRlZCBuZWVkZWRcblx0XHRleHBvcnRzOiB7fVxuXHR9O1xuXG5cdC8vIEV4ZWN1dGUgdGhlIG1vZHVsZSBmdW5jdGlvblxuXHRfX3dlYnBhY2tfbW9kdWxlc19fW21vZHVsZUlkXShtb2R1bGUsIG1vZHVsZS5leHBvcnRzLCBfX3dlYnBhY2tfcmVxdWlyZV9fKTtcblxuXHQvLyBSZXR1cm4gdGhlIGV4cG9ydHMgb2YgdGhlIG1vZHVsZVxuXHRyZXR1cm4gbW9kdWxlLmV4cG9ydHM7XG59XG5cbiIsIi8vIGdldERlZmF1bHRFeHBvcnQgZnVuY3Rpb24gZm9yIGNvbXBhdGliaWxpdHkgd2l0aCBub24taGFybW9ueSBtb2R1bGVzXG5fX3dlYnBhY2tfcmVxdWlyZV9fLm4gPSAobW9kdWxlKSA9PiB7XG5cdHZhciBnZXR0ZXIgPSBtb2R1bGUgJiYgbW9kdWxlLl9fZXNNb2R1bGUgP1xuXHRcdCgpID0+IChtb2R1bGVbJ2RlZmF1bHQnXSkgOlxuXHRcdCgpID0+IChtb2R1bGUpO1xuXHRfX3dlYnBhY2tfcmVxdWlyZV9fLmQoZ2V0dGVyLCB7IGE6IGdldHRlciB9KTtcblx0cmV0dXJuIGdldHRlcjtcbn07IiwiLy8gZGVmaW5lIGdldHRlciBmdW5jdGlvbnMgZm9yIGhhcm1vbnkgZXhwb3J0c1xuX193ZWJwYWNrX3JlcXVpcmVfXy5kID0gKGV4cG9ydHMsIGRlZmluaXRpb24pID0+IHtcblx0Zm9yKHZhciBrZXkgaW4gZGVmaW5pdGlvbikge1xuXHRcdGlmKF9fd2VicGFja19yZXF1aXJlX18ubyhkZWZpbml0aW9uLCBrZXkpICYmICFfX3dlYnBhY2tfcmVxdWlyZV9fLm8oZXhwb3J0cywga2V5KSkge1xuXHRcdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsIGtleSwgeyBlbnVtZXJhYmxlOiB0cnVlLCBnZXQ6IGRlZmluaXRpb25ba2V5XSB9KTtcblx0XHR9XG5cdH1cbn07IiwiX193ZWJwYWNrX3JlcXVpcmVfXy5vID0gKG9iaiwgcHJvcCkgPT4gKE9iamVjdC5wcm90b3R5cGUuaGFzT3duUHJvcGVydHkuY2FsbChvYmosIHByb3ApKSIsIi8vIGRlZmluZSBfX2VzTW9kdWxlIG9uIGV4cG9ydHNcbl9fd2VicGFja19yZXF1aXJlX18uciA9IChleHBvcnRzKSA9PiB7XG5cdGlmKHR5cGVvZiBTeW1ib2wgIT09ICd1bmRlZmluZWQnICYmIFN5bWJvbC50b1N0cmluZ1RhZykge1xuXHRcdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBTeW1ib2wudG9TdHJpbmdUYWcsIHsgdmFsdWU6ICdNb2R1bGUnIH0pO1xuXHR9XG5cdE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCAnX19lc01vZHVsZScsIHsgdmFsdWU6IHRydWUgfSk7XG59OyIsImV4cG9ydCBjb25zdCBOYW5vZmxvd0NvbW1vbnMkU2hvd1Byb2dyZXNzID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL1RLQS9Eb2N1bWVudHMvTWVuZGl4L1F1aXpBcHAvamF2YXNjcmlwdHNvdXJjZS9uYW5vZmxvd2NvbW1vbnMvYWN0aW9ucy9TaG93UHJvZ3Jlc3NcIikpLlNob3dQcm9ncmVzcztcbmV4cG9ydCBjb25zdCBOYW5vZmxvd0NvbW1vbnMkSGlkZVByb2dyZXNzID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL1RLQS9Eb2N1bWVudHMvTWVuZGl4L1F1aXpBcHAvamF2YXNjcmlwdHNvdXJjZS9uYW5vZmxvd2NvbW1vbnMvYWN0aW9ucy9IaWRlUHJvZ3Jlc3NcIikpLkhpZGVQcm9ncmVzcztcbmV4cG9ydCBjb25zdCBCdWlsZGVyJEpTX0ZpeF9PblF1ZXN0aW9uQ2hhbmdlID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL1RLQS9Eb2N1bWVudHMvTWVuZGl4L1F1aXpBcHAvamF2YXNjcmlwdHNvdXJjZS9idWlsZGVyL2FjdGlvbnMvSlNfRml4X09uUXVlc3Rpb25DaGFuZ2VcIikpLkpTX0ZpeF9PblF1ZXN0aW9uQ2hhbmdlO1xuZXhwb3J0IGNvbnN0IEJ1aWxkZXIkSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlID0gYXN5bmMgKCkgPT4gKGF3YWl0IGltcG9ydChcIkM6L1VzZXJzL1RLQS9Eb2N1bWVudHMvTWVuZGl4L1F1aXpBcHAvamF2YXNjcmlwdHNvdXJjZS9idWlsZGVyL2FjdGlvbnMvSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlXCIpKS5KU19GaXhfT25RdWVzdGlvbkJvZHlDaGFuZ2U7XG4iXSwibmFtZXMiOlsiQmlnIiwiSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlIiwicXVlc3Rpb24iLCJpc1dyYXBwZWQiLCJzdHJIVE1MIiwic3RhcnRzV2l0aCIsImVuZHNXaXRoIiwid3JhcCIsInBsYWNlQ2FyZXRBdEVuZCIsImVsIiwiZm9jdXMiLCJ3aW5kb3ciLCJnZXRTZWxlY3Rpb24iLCJkb2N1bWVudCIsImNyZWF0ZVJhbmdlIiwicmFuZ2UiLCJzZWxlY3ROb2RlQ29udGVudHMiLCJjb2xsYXBzZSIsInNlbCIsInJlbW92ZUFsbFJhbmdlcyIsImFkZFJhbmdlIiwiYm9keSIsImNyZWF0ZVRleHRSYW5nZSIsInRleHRSYW5nZSIsIm1vdmVUb0VsZW1lbnRUZXh0Iiwic2VsZWN0IiwicXVlc3Rpb25Cb2R5IiwiZ2V0IiwidGV4dEVkaXRvciIsImdldEVsZW1lbnRzQnlDbGFzc05hbWUiLCJ3cmFwcGVkIiwiaW5uZXJIVE1MIiwiSlNfRml4X09uUXVlc3Rpb25DaGFuZ2UiLCJIaWRlUHJvZ3Jlc3MiLCJpZGVudGlmaWVyIiwiUHJvbWlzZSIsInJlamVjdCIsIkVycm9yIiwibXgiLCJ1aSIsImhpZGVQcm9ncmVzcyIsIk51bWJlciIsInJlc29sdmUiLCJTaG93UHJvZ3Jlc3MiLCJtZXNzYWdlIiwiYmxvY2tpbmciLCJpZCIsInNob3dQcm9ncmVzcyIsInVuZGVmaW5lZCIsIk5hbm9mbG93Q29tbW9ucyRTaG93UHJvZ3Jlc3MiLCJOYW5vZmxvd0NvbW1vbnMkSGlkZVByb2dyZXNzIiwiQnVpbGRlciRKU19GaXhfT25RdWVzdGlvbkNoYW5nZSIsIkJ1aWxkZXIkSlNfRml4X09uUXVlc3Rpb25Cb2R5Q2hhbmdlIl0sInNvdXJjZVJvb3QiOiIifQ==