// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package extensions.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Extensions module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Account_ByCurrentUserBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Extensions.SUB_Account_ByCurrentUser");
		return builder;
	}

	public static administration.proxies.Account sUB_Account_ByCurrentUser(IContext context)
	{
		Object result = sUB_Account_ByCurrentUserBuilder().execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_IsOwnerOfObjectBuilder(
		quizapp.proxies.RemoteObject _remoteObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Extensions.SUB_IsOwnerOfObject");
		builder = builder.withParam("RemoteObject", _remoteObject);
		return builder;
	}

	public static boolean sUB_IsOwnerOfObject(
		IContext context,
		quizapp.proxies.RemoteObject _remoteObject
	)
	{
		Object result = sUB_IsOwnerOfObjectBuilder(
				_remoteObject
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_UserRole_FromCurrentUserBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Extensions.SUB_UserRole_FromCurrentUser");
		return builder;
	}

	public static system.proxies.UserRole sUB_UserRole_FromCurrentUser(IContext context)
	{
		Object result = sUB_UserRole_FromCurrentUserBuilder().execute(context);
		return result == null ? null : system.proxies.UserRole.initialize(context, (IMendixObject) result);
	}
}
