// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oql.proxies;

public class ExamplePerson implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject examplePersonMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OQL.ExamplePerson";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Name("Name"),
		DateOfBirth("DateOfBirth"),
		Age("Age"),
		LongAge("LongAge"),
		Active("Active"),
		HeightInDecimal("HeightInDecimal"),
		Gender("Gender"),
		MarriedTo("OQL.MarriedTo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExamplePerson(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ExamplePerson(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject examplePersonMendixObject)
	{
		if (examplePersonMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, examplePersonMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.examplePersonMendixObject = examplePersonMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static oql.proxies.ExamplePerson initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oql.proxies.ExamplePerson(context, mendixObject);
	}

	public static oql.proxies.ExamplePerson load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oql.proxies.ExamplePerson.initialize(context, mendixObject);
	}

	public static java.util.List<oql.proxies.ExamplePerson> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> oql.proxies.ExamplePerson.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Long getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Long getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Long number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * @return value of Age
	 */
	public final java.lang.Integer getAge()
	{
		return getAge(getContext());
	}

	/**
	 * @param context
	 * @return value of Age
	 */
	public final java.lang.Integer getAge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Age.toString());
	}

	/**
	 * Set value of Age
	 * @param age
	 */
	public final void setAge(java.lang.Integer age)
	{
		setAge(getContext(), age);
	}

	/**
	 * Set value of Age
	 * @param context
	 * @param age
	 */
	public final void setAge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer age)
	{
		getMendixObject().setValue(context, MemberNames.Age.toString(), age);
	}

	/**
	 * @return value of LongAge
	 */
	public final java.lang.Long getLongAge()
	{
		return getLongAge(getContext());
	}

	/**
	 * @param context
	 * @return value of LongAge
	 */
	public final java.lang.Long getLongAge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LongAge.toString());
	}

	/**
	 * Set value of LongAge
	 * @param longage
	 */
	public final void setLongAge(java.lang.Long longage)
	{
		setLongAge(getContext(), longage);
	}

	/**
	 * Set value of LongAge
	 * @param context
	 * @param longage
	 */
	public final void setLongAge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long longage)
	{
		getMendixObject().setValue(context, MemberNames.LongAge.toString(), longage);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of HeightInDecimal
	 */
	public final java.math.BigDecimal getHeightInDecimal()
	{
		return getHeightInDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of HeightInDecimal
	 */
	public final java.math.BigDecimal getHeightInDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.HeightInDecimal.toString());
	}

	/**
	 * Set value of HeightInDecimal
	 * @param heightindecimal
	 */
	public final void setHeightInDecimal(java.math.BigDecimal heightindecimal)
	{
		setHeightInDecimal(getContext(), heightindecimal);
	}

	/**
	 * Set value of HeightInDecimal
	 * @param context
	 * @param heightindecimal
	 */
	public final void setHeightInDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal heightindecimal)
	{
		getMendixObject().setValue(context, MemberNames.HeightInDecimal.toString(), heightindecimal);
	}

	/**
	 * Get value of Gender
	 * @param gender
	 */
	public final oql.proxies.Gender getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final oql.proxies.Gender getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Gender.toString());
		if (obj == null) {
			return null;
		}
		return oql.proxies.Gender.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(oql.proxies.Gender gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, oql.proxies.Gender gender)
	{
		if (gender != null) {
			getMendixObject().setValue(context, MemberNames.Gender.toString(), gender.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Gender.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MarriedTo
	 */
	public final oql.proxies.ExamplePerson getMarriedTo() throws com.mendix.core.CoreException
	{
		return getMarriedTo(getContext());
	}

	/**
	 * @param context
	 * @return value of MarriedTo
	 * @throws com.mendix.core.CoreException
	 */
	public final oql.proxies.ExamplePerson getMarriedTo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		oql.proxies.ExamplePerson result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MarriedTo.toString());
		if (identifier != null) {
			result = oql.proxies.ExamplePerson.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MarriedTo
	 * @param marriedto
	 */
	public final void setMarriedTo(oql.proxies.ExamplePerson marriedto)
	{
		setMarriedTo(getContext(), marriedto);
	}

	/**
	 * Set value of MarriedTo
	 * @param context
	 * @param marriedto
	 */
	public final void setMarriedTo(com.mendix.systemwideinterfaces.core.IContext context, oql.proxies.ExamplePerson marriedto)
	{
		if (marriedto == null) {
			getMendixObject().setValue(context, MemberNames.MarriedTo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MarriedTo.toString(), marriedto.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return examplePersonMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oql.proxies.ExamplePerson that = (oql.proxies.ExamplePerson) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
