// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package solver.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Solver module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_GenerateSolverTestBuilder(
		builder.proxies.ConnectedSelector _connectedSelector,
		builder.proxies.TestHelper _testHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Solver.ACT_GenerateSolverTest");
		builder = builder.withParam("ConnectedSelector", _connectedSelector);
		builder = builder.withParam("TestHelper", _testHelper);
		return builder;
	}

	public static void aCT_GenerateSolverTest(
		IContext context,
		builder.proxies.ConnectedSelector _connectedSelector,
		builder.proxies.TestHelper _testHelper
	)
	{
		aCT_GenerateSolverTestBuilder(
				_connectedSelector,
				_testHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ActiveSolverQuestionBuilder(
		builder.proxies.TestHelper _testHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Solver.DS_ActiveSolverQuestion");
		builder = builder.withParam("TestHelper", _testHelper);
		return builder;
	}

	public static solver.proxies.SolverQuestion dS_ActiveSolverQuestion(
		IContext context,
		builder.proxies.TestHelper _testHelper
	)
	{
		Object result = dS_ActiveSolverQuestionBuilder(
				_testHelper
			)
			.execute(context);
		return result == null ? null : solver.proxies.SolverQuestion.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_QuestionList_GetBy_LectureBuilder(
		builder.proxies.Lecture _lecture
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Solver.SUB_QuestionList_GetBy_Lecture");
		builder = builder.withParam("Lecture", _lecture);
		return builder;
	}

	public static java.util.List<builder.proxies.Question> sUB_QuestionList_GetBy_Lecture(
		IContext context,
		builder.proxies.Lecture _lecture
	)
	{
		Object result = sUB_QuestionList_GetBy_LectureBuilder(
				_lecture
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> builder.proxies.Question.initialize(context, obj));
	}
}
