// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dataservice.proxies;

public class DS_QuestionArray implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dS_QuestionArrayMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataService.DS_QuestionArray";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DS_QuestionArray_DS_Test("DataService.DS_QuestionArray_DS_Test");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DS_QuestionArray(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DS_QuestionArray(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dS_QuestionArrayMendixObject)
	{
		if (dS_QuestionArrayMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dS_QuestionArrayMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dS_QuestionArrayMendixObject = dS_QuestionArrayMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dataservice.proxies.DS_QuestionArray initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dataservice.proxies.DS_QuestionArray(context, mendixObject);
	}

	public static dataservice.proxies.DS_QuestionArray load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dataservice.proxies.DS_QuestionArray.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DS_QuestionArray_DS_Test
	 */
	public final dataservice.proxies.DS_Test getDS_QuestionArray_DS_Test() throws com.mendix.core.CoreException
	{
		return getDS_QuestionArray_DS_Test(getContext());
	}

	/**
	 * @param context
	 * @return value of DS_QuestionArray_DS_Test
	 * @throws com.mendix.core.CoreException
	 */
	public final dataservice.proxies.DS_Test getDS_QuestionArray_DS_Test(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dataservice.proxies.DS_Test result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DS_QuestionArray_DS_Test.toString());
		if (identifier != null) {
			result = dataservice.proxies.DS_Test.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DS_QuestionArray_DS_Test
	 * @param ds_questionarray_ds_test
	 */
	public final void setDS_QuestionArray_DS_Test(dataservice.proxies.DS_Test ds_questionarray_ds_test)
	{
		setDS_QuestionArray_DS_Test(getContext(), ds_questionarray_ds_test);
	}

	/**
	 * Set value of DS_QuestionArray_DS_Test
	 * @param context
	 * @param ds_questionarray_ds_test
	 */
	public final void setDS_QuestionArray_DS_Test(com.mendix.systemwideinterfaces.core.IContext context, dataservice.proxies.DS_Test ds_questionarray_ds_test)
	{
		if (ds_questionarray_ds_test == null) {
			getMendixObject().setValue(context, MemberNames.DS_QuestionArray_DS_Test.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DS_QuestionArray_DS_Test.toString(), ds_questionarray_ds_test.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dS_QuestionArrayMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dataservice.proxies.DS_QuestionArray that = (dataservice.proxies.DS_QuestionArray) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
