// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dataservice.proxies;

public class DS_TestRoot implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dS_TestRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataService.DS_TestRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DS_TestArray_DS_TestRoot("DataService.DS_TestArray_DS_TestRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DS_TestRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DS_TestRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dS_TestRootMendixObject)
	{
		if (dS_TestRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dS_TestRootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dS_TestRootMendixObject = dS_TestRootMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dataservice.proxies.DS_TestRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dataservice.proxies.DS_TestRoot(context, mendixObject);
	}

	public static dataservice.proxies.DS_TestRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dataservice.proxies.DS_TestRoot.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DS_TestArray_DS_TestRoot
	 */
	public final dataservice.proxies.DS_TestArray getDS_TestArray_DS_TestRoot() throws com.mendix.core.CoreException
	{
		return getDS_TestArray_DS_TestRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of DS_TestArray_DS_TestRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final dataservice.proxies.DS_TestArray getDS_TestArray_DS_TestRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dataservice.proxies.DS_TestArray result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DS_TestArray_DS_TestRoot.toString());
		if (identifier != null) {
			result = dataservice.proxies.DS_TestArray.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DS_TestArray_DS_TestRoot
	 * @param ds_testarray_ds_testroot
	 */
	public final void setDS_TestArray_DS_TestRoot(dataservice.proxies.DS_TestArray ds_testarray_ds_testroot)
	{
		setDS_TestArray_DS_TestRoot(getContext(), ds_testarray_ds_testroot);
	}

	/**
	 * Set value of DS_TestArray_DS_TestRoot
	 * @param context
	 * @param ds_testarray_ds_testroot
	 */
	public final void setDS_TestArray_DS_TestRoot(com.mendix.systemwideinterfaces.core.IContext context, dataservice.proxies.DS_TestArray ds_testarray_ds_testroot)
	{
		if (ds_testarray_ds_testroot == null) {
			getMendixObject().setValue(context, MemberNames.DS_TestArray_DS_TestRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DS_TestArray_DS_TestRoot.toString(), ds_testarray_ds_testroot.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dS_TestRootMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dataservice.proxies.DS_TestRoot that = (dataservice.proxies.DS_TestRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
