// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oql.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the OQL module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ExecuteOQLBuilder(
		oql.proxies.Query _query
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OQL.ACT_ExecuteOQL");
		builder = builder.withParam("Query", _query);
		return builder;
	}

	public static void aCT_ExecuteOQL(
		IContext context,
		oql.proxies.Query _query
	)
	{
		aCT_ExecuteOQLBuilder(
				_query
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ExampleOQL_DataSetBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OQL.DS_ExampleOQL_DataSet");
		return builder;
	}

	public static java.util.List<oql.proxies.ExamplePersonResult> dS_ExampleOQL_DataSet(IContext context)
	{
		Object result = dS_ExampleOQL_DataSetBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> oql.proxies.ExamplePersonResult.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ExampleOQL_StatementBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OQL.DS_ExampleOQL_Statement");
		return builder;
	}

	public static java.util.List<oql.proxies.ExamplePersonResult> dS_ExampleOQL_Statement(IContext context)
	{
		Object result = dS_ExampleOQL_StatementBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> oql.proxies.ExamplePersonResult.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetQueryBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OQL.DS_GetQuery");
		return builder;
	}

	public static oql.proxies.Query dS_GetQuery(IContext context)
	{
		Object result = dS_GetQueryBuilder().execute(context);
		return result == null ? null : oql.proxies.Query.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_CreateContentBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OQL.IVK_CreateContent");
		return builder;
	}

	public static void iVK_CreateContent(IContext context)
	{
		iVK_CreateContentBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_PerformTestsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OQL.IVK_PerformTests");
		return builder;
	}

	public static void iVK_PerformTests(IContext context)
	{
		iVK_PerformTestsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_TestCountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("OQL.IVK_TestCount");
		return builder;
	}

	public static void iVK_TestCount(IContext context)
	{
		iVK_TestCountBuilder().execute(context);
	}
}
