// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the DocumentGeneration module

	/**
	* URL of the DocGen Cloud Service API
	* 
	* Default: https://docgen.home.mendix.com/v1/generate-document
	*/
	public static java.lang.String getAPI_URL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DocumentGeneration.API_URL");
	}

	/**
	* Timeout in seconds for an asynchronous request; determines how long a document is allowed to be queued by the Cloud service
	*/
	public static java.lang.Long getAsyncTimeoutInSeconds()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("DocumentGeneration.AsyncTimeoutInSeconds");
	}

	/**
	* Path to Chrome or Chromium executable, for example: C:/Program Files/Google/Chrome/Application/Chrome.exe
	*/
	public static java.lang.String getCustomChromePath()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DocumentGeneration.CustomChromePath");
	}

	public static boolean getEmulateCloudEnvironment()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("DocumentGeneration.EmulateCloudEnvironment");
	}

	/**
	* The number of hours to determine if the access token that is used to secure the Document Generation Cloud service should be refreshed.
	*/
	public static java.lang.Long getMaxHoursBeforeTokenRefresh()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("DocumentGeneration.MaxHoursBeforeTokenRefresh");
	}

	/**
	* The offset in days after which expired DocumentRequest objects are deleted if the 'SE_DocumentRequest_Cleanup' scheduled event has been enabled.
	* 
	* Default: 7 days.
	*/
	public static java.lang.Long getRequestCleanupOffsetInDays()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("DocumentGeneration.RequestCleanupOffsetInDays");
	}

	/**
	* Timeout in seconds for a synchronous request to wait for the result
	*/
	public static java.lang.Long getSyncTimeoutInSeconds()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("DocumentGeneration.SyncTimeoutInSeconds");
	}

	/**
	* URL of the DocGen App Registration API
	* 
	* Default: https://docgen.home.mendix.com/auth/v1/token
	*/
	public static java.lang.String getTOKEN_URL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DocumentGeneration.TOKEN_URL");
	}

	/**
	* Security token lifetime in seconds. The security token is used to secure and validate document requests from the local and/or cloud service.
	* 
	* Default value: 1800 (30 minutes)
	*/
	public static java.lang.Long getTokenLifetimeInSeconds()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("DocumentGeneration.TokenLifetimeInSeconds");
	}

	/**
	* This is the version of the Document Generation module.
	*/
	public static java.lang.String getVersion()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DocumentGeneration.Version");
	}
}