// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package solver.proxies;

public enum ENUM_TestStatus
{
	Config(new java.lang.String[][] { new java.lang.String[] { "en_US", "Config" } }),
	Started(new java.lang.String[][] { new java.lang.String[] { "en_US", "Started" } }),
	Finished(new java.lang.String[][] { new java.lang.String[] { "en_US", "Finished" } }),
	Review(new java.lang.String[][] { new java.lang.String[] { "en_US", "Review" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_TestStatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
