// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public class DocumentRequest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject documentRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DocumentGeneration.DocumentRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RequestId("RequestId"),
		FileName("FileName"),
		ResultEntity("ResultEntity"),
		MicroflowName("MicroflowName"),
		ContextObjectGuid("ContextObjectGuid"),
		SecurityToken("SecurityToken"),
		ExpirationDate("ExpirationDate"),
		DocumentRequest_Session("DocumentGeneration.DocumentRequest_Session"),
		DocumentRequest_FileDocument("DocumentGeneration.DocumentRequest_FileDocument"),
		DocumentRequest_DocumentUser("DocumentGeneration.DocumentRequest_DocumentUser");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocumentRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DocumentRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentRequestMendixObject)
	{
		if (documentRequestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, documentRequestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.documentRequestMendixObject = documentRequestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static documentgeneration.proxies.DocumentRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new documentgeneration.proxies.DocumentRequest(context, mendixObject);
	}

	public static documentgeneration.proxies.DocumentRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return documentgeneration.proxies.DocumentRequest.initialize(context, mendixObject);
	}

	public static java.util.List<documentgeneration.proxies.DocumentRequest> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> documentgeneration.proxies.DocumentRequest.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of RequestId
	 */
	public final java.lang.String getRequestId()
	{
		return getRequestId(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestId
	 */
	public final java.lang.String getRequestId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestId.toString());
	}

	/**
	 * Set value of RequestId
	 * @param requestid
	 */
	public final void setRequestId(java.lang.String requestid)
	{
		setRequestId(getContext(), requestid);
	}

	/**
	 * Set value of RequestId
	 * @param context
	 * @param requestid
	 */
	public final void setRequestId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestid)
	{
		getMendixObject().setValue(context, MemberNames.RequestId.toString(), requestid);
	}

	/**
	 * @return value of FileName
	 */
	public final java.lang.String getFileName()
	{
		return getFileName(getContext());
	}

	/**
	 * @param context
	 * @return value of FileName
	 */
	public final java.lang.String getFileName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FileName.toString());
	}

	/**
	 * Set value of FileName
	 * @param filename
	 */
	public final void setFileName(java.lang.String filename)
	{
		setFileName(getContext(), filename);
	}

	/**
	 * Set value of FileName
	 * @param context
	 * @param filename
	 */
	public final void setFileName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filename)
	{
		getMendixObject().setValue(context, MemberNames.FileName.toString(), filename);
	}

	/**
	 * @return value of ResultEntity
	 */
	public final java.lang.String getResultEntity()
	{
		return getResultEntity(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultEntity
	 */
	public final java.lang.String getResultEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ResultEntity.toString());
	}

	/**
	 * Set value of ResultEntity
	 * @param resultentity
	 */
	public final void setResultEntity(java.lang.String resultentity)
	{
		setResultEntity(getContext(), resultentity);
	}

	/**
	 * Set value of ResultEntity
	 * @param context
	 * @param resultentity
	 */
	public final void setResultEntity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String resultentity)
	{
		getMendixObject().setValue(context, MemberNames.ResultEntity.toString(), resultentity);
	}

	/**
	 * @return value of MicroflowName
	 */
	public final java.lang.String getMicroflowName()
	{
		return getMicroflowName(getContext());
	}

	/**
	 * @param context
	 * @return value of MicroflowName
	 */
	public final java.lang.String getMicroflowName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MicroflowName.toString());
	}

	/**
	 * Set value of MicroflowName
	 * @param microflowname
	 */
	public final void setMicroflowName(java.lang.String microflowname)
	{
		setMicroflowName(getContext(), microflowname);
	}

	/**
	 * Set value of MicroflowName
	 * @param context
	 * @param microflowname
	 */
	public final void setMicroflowName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String microflowname)
	{
		getMendixObject().setValue(context, MemberNames.MicroflowName.toString(), microflowname);
	}

	/**
	 * @return value of ContextObjectGuid
	 */
	public final java.lang.Long getContextObjectGuid()
	{
		return getContextObjectGuid(getContext());
	}

	/**
	 * @param context
	 * @return value of ContextObjectGuid
	 */
	public final java.lang.Long getContextObjectGuid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ContextObjectGuid.toString());
	}

	/**
	 * Set value of ContextObjectGuid
	 * @param contextobjectguid
	 */
	public final void setContextObjectGuid(java.lang.Long contextobjectguid)
	{
		setContextObjectGuid(getContext(), contextobjectguid);
	}

	/**
	 * Set value of ContextObjectGuid
	 * @param context
	 * @param contextobjectguid
	 */
	public final void setContextObjectGuid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long contextobjectguid)
	{
		getMendixObject().setValue(context, MemberNames.ContextObjectGuid.toString(), contextobjectguid);
	}

	/**
	 * Set value of SecurityToken
	 * @param securitytoken
	 */
	public final void setSecurityToken(java.lang.String securitytoken)
	{
		setSecurityToken(getContext(), securitytoken);
	}

	/**
	 * Set value of SecurityToken
	 * @param context
	 * @param securitytoken
	 */
	public final void setSecurityToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String securitytoken)
	{
		getMendixObject().setValue(context, MemberNames.SecurityToken.toString(), securitytoken);
	}

	/**
	 * @return value of ExpirationDate
	 */
	public final java.util.Date getExpirationDate()
	{
		return getExpirationDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpirationDate
	 */
	public final java.util.Date getExpirationDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpirationDate.toString());
	}

	/**
	 * Set value of ExpirationDate
	 * @param expirationdate
	 */
	public final void setExpirationDate(java.util.Date expirationdate)
	{
		setExpirationDate(getContext(), expirationdate);
	}

	/**
	 * Set value of ExpirationDate
	 * @param context
	 * @param expirationdate
	 */
	public final void setExpirationDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expirationdate)
	{
		getMendixObject().setValue(context, MemberNames.ExpirationDate.toString(), expirationdate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DocumentRequest_Session
	 */
	public final system.proxies.Session getDocumentRequest_Session() throws com.mendix.core.CoreException
	{
		return getDocumentRequest_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentRequest_Session
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Session getDocumentRequest_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentRequest_Session.toString());
		if (identifier != null) {
			result = system.proxies.Session.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DocumentRequest_Session
	 * @param documentrequest_session
	 */
	public final void setDocumentRequest_Session(system.proxies.Session documentrequest_session)
	{
		setDocumentRequest_Session(getContext(), documentrequest_session);
	}

	/**
	 * Set value of DocumentRequest_Session
	 * @param context
	 * @param documentrequest_session
	 */
	public final void setDocumentRequest_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session documentrequest_session)
	{
		if (documentrequest_session == null) {
			getMendixObject().setValue(context, MemberNames.DocumentRequest_Session.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DocumentRequest_Session.toString(), documentrequest_session.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DocumentRequest_FileDocument
	 */
	public final system.proxies.FileDocument getDocumentRequest_FileDocument() throws com.mendix.core.CoreException
	{
		return getDocumentRequest_FileDocument(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentRequest_FileDocument
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.FileDocument getDocumentRequest_FileDocument(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.FileDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentRequest_FileDocument.toString());
		if (identifier != null) {
			result = system.proxies.FileDocument.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DocumentRequest_FileDocument
	 * @param documentrequest_filedocument
	 */
	public final void setDocumentRequest_FileDocument(system.proxies.FileDocument documentrequest_filedocument)
	{
		setDocumentRequest_FileDocument(getContext(), documentrequest_filedocument);
	}

	/**
	 * Set value of DocumentRequest_FileDocument
	 * @param context
	 * @param documentrequest_filedocument
	 */
	public final void setDocumentRequest_FileDocument(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.FileDocument documentrequest_filedocument)
	{
		if (documentrequest_filedocument == null) {
			getMendixObject().setValue(context, MemberNames.DocumentRequest_FileDocument.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DocumentRequest_FileDocument.toString(), documentrequest_filedocument.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DocumentRequest_DocumentUser
	 */
	public final system.proxies.User getDocumentRequest_DocumentUser() throws com.mendix.core.CoreException
	{
		return getDocumentRequest_DocumentUser(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentRequest_DocumentUser
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.User getDocumentRequest_DocumentUser(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DocumentRequest_DocumentUser.toString());
		if (identifier != null) {
			result = system.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DocumentRequest_DocumentUser
	 * @param documentrequest_documentuser
	 */
	public final void setDocumentRequest_DocumentUser(system.proxies.User documentrequest_documentuser)
	{
		setDocumentRequest_DocumentUser(getContext(), documentrequest_documentuser);
	}

	/**
	 * Set value of DocumentRequest_DocumentUser
	 * @param context
	 * @param documentrequest_documentuser
	 */
	public final void setDocumentRequest_DocumentUser(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User documentrequest_documentuser)
	{
		if (documentrequest_documentuser == null) {
			getMendixObject().setValue(context, MemberNames.DocumentRequest_DocumentUser.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DocumentRequest_DocumentUser.toString(), documentrequest_documentuser.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return documentRequestMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final documentgeneration.proxies.DocumentRequest that = (documentgeneration.proxies.DocumentRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
