// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package randomobject.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns a random item from a list with objects.
 */
public class GetRandomObjectFromList extends CustomJavaAction<IMendixObject>
{
	private final java.util.List<IMendixObject> List;

	public GetRandomObjectFromList(
		IContext context,
		java.util.List<IMendixObject> _list
	)
	{
		super(context);
		this.List = _list;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try { 
			int n = List.size();
			if( n == 0 ) {
				return null;
			}
			else {
				int i = (int)Math.floor(Math.random()*n);
				return List.get(i);			
			}
		} catch (Exception e) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Retrieve of random object failed");
		}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetRandomObjectFromList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
