// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package builder.proxies;

public enum ENUM_Answer
{
	A(new java.lang.String[][] { new java.lang.String[] { "en_US", "A" } }),
	B(new java.lang.String[][] { new java.lang.String[] { "en_US", "B" } }),
	C(new java.lang.String[][] { new java.lang.String[] { "en_US", "C" } }),
	D(new java.lang.String[][] { new java.lang.String[] { "en_US", "D" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_Answer(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
