// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package builder.proxies;

public class School extends quizapp.proxies.RemoteObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Builder.School";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SchoolId("SchoolId"),
		SchoolType("SchoolType"),
		_Id("_Id"),
		CustomCreatedDate("CustomCreatedDate"),
		CustomChangedDate("CustomChangedDate"),
		CustomCreatedDateAsLong("CustomCreatedDateAsLong"),
		CustomChangedDateAsLong("CustomChangedDateAsLong"),
		RemoteObject_Account_CreatedBy("QuizApp.RemoteObject_Account_CreatedBy"),
		RemoteObject_Account_ChangedBy("QuizApp.RemoteObject_Account_ChangedBy");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public School(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected School(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject schoolMendixObject)
	{
		super(context, schoolMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, schoolMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static builder.proxies.School initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new builder.proxies.School(context, mendixObject);
	}

	public static builder.proxies.School load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return builder.proxies.School.initialize(context, mendixObject);
	}

	public static java.util.List<builder.proxies.School> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> builder.proxies.School.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of SchoolId
	 */
	public final java.lang.Long getSchoolId()
	{
		return getSchoolId(getContext());
	}

	/**
	 * @param context
	 * @return value of SchoolId
	 */
	public final java.lang.Long getSchoolId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SchoolId.toString());
	}

	/**
	 * Set value of SchoolId
	 * @param schoolid
	 */
	public final void setSchoolId(java.lang.Long schoolid)
	{
		setSchoolId(getContext(), schoolid);
	}

	/**
	 * Set value of SchoolId
	 * @param context
	 * @param schoolid
	 */
	public final void setSchoolId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long schoolid)
	{
		getMendixObject().setValue(context, MemberNames.SchoolId.toString(), schoolid);
	}

	/**
	 * @return value of SchoolType
	 */
	public final java.lang.String getSchoolType()
	{
		return getSchoolType(getContext());
	}

	/**
	 * @param context
	 * @return value of SchoolType
	 */
	public final java.lang.String getSchoolType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SchoolType.toString());
	}

	/**
	 * Set value of SchoolType
	 * @param schooltype
	 */
	public final void setSchoolType(java.lang.String schooltype)
	{
		setSchoolType(getContext(), schooltype);
	}

	/**
	 * Set value of SchoolType
	 * @param context
	 * @param schooltype
	 */
	public final void setSchoolType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String schooltype)
	{
		getMendixObject().setValue(context, MemberNames.SchoolType.toString(), schooltype);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final builder.proxies.School that = (builder.proxies.School) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
