// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package builder.proxies;

public class TestHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Builder.TestHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TestStatus("TestStatus"),
		ActiveQuestionSort("ActiveQuestionSort"),
		BeginDate("BeginDate"),
		TestHelper_Test("Builder.TestHelper_Test"),
		TestHelper_ConnectedSelector("Builder.TestHelper_ConnectedSelector"),
		TestHelper_SolverTest("Builder.TestHelper_SolverTest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testHelperMendixObject)
	{
		if (testHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, testHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testHelperMendixObject = testHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static builder.proxies.TestHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new builder.proxies.TestHelper(context, mendixObject);
	}

	public static builder.proxies.TestHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return builder.proxies.TestHelper.initialize(context, mendixObject);
	}

	/**
	 * Get value of TestStatus
	 * @param teststatus
	 */
	public final solver.proxies.ENUM_TestStatus getTestStatus()
	{
		return getTestStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of TestStatus
	 */
	public final solver.proxies.ENUM_TestStatus getTestStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TestStatus.toString());
		if (obj == null) {
			return null;
		}
		return solver.proxies.ENUM_TestStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TestStatus
	 * @param teststatus
	 */
	public final void setTestStatus(solver.proxies.ENUM_TestStatus teststatus)
	{
		setTestStatus(getContext(), teststatus);
	}

	/**
	 * Set value of TestStatus
	 * @param context
	 * @param teststatus
	 */
	public final void setTestStatus(com.mendix.systemwideinterfaces.core.IContext context, solver.proxies.ENUM_TestStatus teststatus)
	{
		if (teststatus != null) {
			getMendixObject().setValue(context, MemberNames.TestStatus.toString(), teststatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TestStatus.toString(), null);
		}
	}

	/**
	 * @return value of ActiveQuestionSort
	 */
	public final java.lang.Integer getActiveQuestionSort()
	{
		return getActiveQuestionSort(getContext());
	}

	/**
	 * @param context
	 * @return value of ActiveQuestionSort
	 */
	public final java.lang.Integer getActiveQuestionSort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ActiveQuestionSort.toString());
	}

	/**
	 * Set value of ActiveQuestionSort
	 * @param activequestionsort
	 */
	public final void setActiveQuestionSort(java.lang.Integer activequestionsort)
	{
		setActiveQuestionSort(getContext(), activequestionsort);
	}

	/**
	 * Set value of ActiveQuestionSort
	 * @param context
	 * @param activequestionsort
	 */
	public final void setActiveQuestionSort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer activequestionsort)
	{
		getMendixObject().setValue(context, MemberNames.ActiveQuestionSort.toString(), activequestionsort);
	}

	/**
	 * @return value of BeginDate
	 */
	public final java.util.Date getBeginDate()
	{
		return getBeginDate(getContext());
	}

	/**
	 * @param context
	 * @return value of BeginDate
	 */
	public final java.util.Date getBeginDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.BeginDate.toString());
	}

	/**
	 * Set value of BeginDate
	 * @param begindate
	 */
	public final void setBeginDate(java.util.Date begindate)
	{
		setBeginDate(getContext(), begindate);
	}

	/**
	 * Set value of BeginDate
	 * @param context
	 * @param begindate
	 */
	public final void setBeginDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date begindate)
	{
		getMendixObject().setValue(context, MemberNames.BeginDate.toString(), begindate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestHelper_Test
	 */
	public final builder.proxies.Test getTestHelper_Test() throws com.mendix.core.CoreException
	{
		return getTestHelper_Test(getContext());
	}

	/**
	 * @param context
	 * @return value of TestHelper_Test
	 * @throws com.mendix.core.CoreException
	 */
	public final builder.proxies.Test getTestHelper_Test(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		builder.proxies.Test result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestHelper_Test.toString());
		if (identifier != null) {
			result = builder.proxies.Test.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestHelper_Test
	 * @param testhelper_test
	 */
	public final void setTestHelper_Test(builder.proxies.Test testhelper_test)
	{
		setTestHelper_Test(getContext(), testhelper_test);
	}

	/**
	 * Set value of TestHelper_Test
	 * @param context
	 * @param testhelper_test
	 */
	public final void setTestHelper_Test(com.mendix.systemwideinterfaces.core.IContext context, builder.proxies.Test testhelper_test)
	{
		if (testhelper_test == null) {
			getMendixObject().setValue(context, MemberNames.TestHelper_Test.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestHelper_Test.toString(), testhelper_test.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestHelper_ConnectedSelector
	 */
	public final builder.proxies.ConnectedSelector getTestHelper_ConnectedSelector() throws com.mendix.core.CoreException
	{
		return getTestHelper_ConnectedSelector(getContext());
	}

	/**
	 * @param context
	 * @return value of TestHelper_ConnectedSelector
	 * @throws com.mendix.core.CoreException
	 */
	public final builder.proxies.ConnectedSelector getTestHelper_ConnectedSelector(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		builder.proxies.ConnectedSelector result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestHelper_ConnectedSelector.toString());
		if (identifier != null) {
			result = builder.proxies.ConnectedSelector.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestHelper_ConnectedSelector
	 * @param testhelper_connectedselector
	 */
	public final void setTestHelper_ConnectedSelector(builder.proxies.ConnectedSelector testhelper_connectedselector)
	{
		setTestHelper_ConnectedSelector(getContext(), testhelper_connectedselector);
	}

	/**
	 * Set value of TestHelper_ConnectedSelector
	 * @param context
	 * @param testhelper_connectedselector
	 */
	public final void setTestHelper_ConnectedSelector(com.mendix.systemwideinterfaces.core.IContext context, builder.proxies.ConnectedSelector testhelper_connectedselector)
	{
		if (testhelper_connectedselector == null) {
			getMendixObject().setValue(context, MemberNames.TestHelper_ConnectedSelector.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestHelper_ConnectedSelector.toString(), testhelper_connectedselector.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TestHelper_SolverTest
	 */
	public final solver.proxies.SolverTest getTestHelper_SolverTest() throws com.mendix.core.CoreException
	{
		return getTestHelper_SolverTest(getContext());
	}

	/**
	 * @param context
	 * @return value of TestHelper_SolverTest
	 * @throws com.mendix.core.CoreException
	 */
	public final solver.proxies.SolverTest getTestHelper_SolverTest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		solver.proxies.SolverTest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestHelper_SolverTest.toString());
		if (identifier != null) {
			result = solver.proxies.SolverTest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TestHelper_SolverTest
	 * @param testhelper_solvertest
	 */
	public final void setTestHelper_SolverTest(solver.proxies.SolverTest testhelper_solvertest)
	{
		setTestHelper_SolverTest(getContext(), testhelper_solvertest);
	}

	/**
	 * Set value of TestHelper_SolverTest
	 * @param context
	 * @param testhelper_solvertest
	 */
	public final void setTestHelper_SolverTest(com.mendix.systemwideinterfaces.core.IContext context, solver.proxies.SolverTest testhelper_solvertest)
	{
		if (testhelper_solvertest == null) {
			getMendixObject().setValue(context, MemberNames.TestHelper_SolverTest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TestHelper_SolverTest.toString(), testhelper_solvertest.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final builder.proxies.TestHelper that = (builder.proxies.TestHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
